# Generated by Django 5.1.5 on 2025-06-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeanalysis',
            name='ats_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
