# Generated by Django 5.1.5 on 2025-06-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_resumeanalysis_ats_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeanalysis',
            name='clarity_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='job_matches',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='skills_match',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
