# Generated by Django 5.1.5 on 2025-06-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_alter_resumeanalysis_clarity_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='strengths',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='weaknesses',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
