# Generated by Django 5.1.5 on 2025-06-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_resumeanalysis_education_resumeanalysis_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeanalysis',
            name='skills_match',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
