# Generated by Django 5.1.5 on 2025-06-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_alter_resumeanalysis_skills_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeanalysis',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
